### PR TITLE
Bump `mamba` pin

### PR DESCRIPTION
**Pull request by dhirschfeld**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dhirschfeld** [comment]
@conda-forge-admin, please rerender

**Comment by dhirschfeld** [comment]
I couldn't see [upstream](https://github.com/mamba-org/boa/) where `mamba` was pinned so I thought I'd put in a PR to loosen it here.

**Comment by dhirschfeld** [comment]
> I couldn't see [upstream](https://github.com/mamba-org/boa/) where `mamba` was pinned so I thought I'd put in a PR to loosen it here.

Also, it seems upstream is testing against 1.2.0:

image

**Comment by dhirschfeld** [comment]
ping @conda-forge/boa!

**Comment by dhirschfeld** [comment]
Well, this hasn't seemed to work. did I stuff something up?

A `mamba update mamba` doesn't pull in `mamba=1.2.0`. Force installing `boa=0.14.0=pyhd8ed1ab_1` seems to downgrade `libsolv` and `libarchive`:

image

After installing `boa=0.14.0=pyhd8ed1ab_1`, `mamba` complains that it still can't update:
```
❯ sudo mamba install mamba=1.2.0

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (1.1.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['mamba=1.2.0']

conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache

Pinned packages:
  - python 3.10.*


Could not solve for environment specs
Encountered problems while solving:
  - package boa-0.14.0-pyhd8ed1ab_1 requires mamba >=1.0,<1.2, but none of the providers can be installed

The environment can't be solved, aborting the operation
```

**Comment by dhirschfeld** [comment]
```
❯ mamba search --info boa=0.14.0=pyhd8ed1ab_1

Loading channels: done
boa 0.14.0 pyhd8ed1ab_1
-----------------------
file name   : boa-0.14.0-pyhd8ed1ab_1.conda
name        : boa
version     : 0.14.0
build       : pyhd8ed1ab_1
build number: 1
size        : 61 KB
license     : BSD-3-Clause
subdir      : noarch
url         : https://conda.anaconda.org/conda-forge/noarch/boa-0.14.0-pyhd8ed1ab_1.conda
md5         : 3e689aa86bdbe9e95ebcf123c2d41347
timestamp   : 2023-02-02 07:24:48 UTC
constraints : 
  - libsolv <0.7.23
dependencies: 
  - conda-build >=3.20,<3.24
  - dataclasses
  - jinja2
  - joblib
  - json5
  - jsonschema
  - mamba >=1.0,<1.2
  - prompt_toolkit
  - python >=3.6
  - rich
  - ruamel.yaml
  - watchgod
  ```

**Comment by dhirschfeld** [comment]
I'm not sure what's going on?!?

CI seems to show that the package being built was `pyhd8ed1ab_1`:

image

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=653135&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=489

---but `anaconda.org` shows that version being uploaded 2 days ago?!?

image


Also, above `mamba` believes that version has a pin `mamba >=1.0,<1.2` when that was the exact pin I relaxed in my PR?!?
https://github.com/conda-forge/boa-feedstock/blob/296eaa65142bbba11b0721bdee527de751d41804/recipe/meta.yaml#L27

https://github.com/conda-forge/boa-feedstock/blame/main/recipe/meta.yaml#L27

**Comment by dhirschfeld** [comment]
@wolfv, @isuruf - do you have any idea what has happened here?

**Comment by dhirschfeld** [comment]
> @wolfv, @isuruf - do you have any idea what has happened here?

I guess with 1.3.0 just published we can try again :/

**Comment by wolfv** [comment]
I think the issue might be that `libsolv` has a run exports, and we're trying to constrain libsolv to a lower number in boa these days to fix an issue blocking the conda release.

**Pull request merged**
