### PR TITLE
Bump `mamba` pin

### PR DESCRIPTION
**Pull request by dhirschfeld**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dhirschfeld** [comment]
@conda-forge-admin, please rerender

**Comment by dhirschfeld** [comment]
2nd time lucky? 🤞 

https://github.com/conda-forge/boa-feedstock/pull/63#issuecomment-1416719273

**Comment by dhirschfeld** [comment]
I guess `boa` just isn't compatible with `mamba>1.1`:
```
❯ micromamba update mamba

conda-forge/noarch                                   9.8MB @   1.3MB/s  7.4s
conda-forge/linux-64                                26.0MB @   1.7MB/s 15.2s

Pinned packages:
  - python 3.10.*

Transaction

  Prefix: /opt/mambaforge/envs/quantdev

  Updating specs:

   - mamba


  Package       Version  Build            Channel                   Size
──────────────────────────────────────────────────────────────────────────
  Change:
──────────────────────────────────────────────────────────────────────────

  - boa          0.14.0  pyhd8ed1ab_1     conda-forge               63kB
  + boa          0.14.0  pyhd8ed1ab_0     conda-forge/noarch        63kB
  - libmamba      1.1.0  h70b1f8a_2       conda-forge                1MB
  + libmamba      1.1.0  hde2b089_3       conda-forge/linux-64       1MB
  - libmambapy    1.1.0  py310h69aa5bf_2  conda-forge              315kB
  + libmambapy    1.1.0  py310h1428755_3  conda-forge/linux-64     312kB
  - mamba         1.1.0  py310h51d5547_2  conda-forge               49kB
  + mamba         1.1.0  py310h51d5547_3  conda-forge/linux-64      50kB

  Upgrade:
──────────────────────────────────────────────────────────────────────────

  - libarchive    3.5.2  hada088e_3       conda-forge                2MB
  + libarchive    3.6.2  h3d51595_0       conda-forge/linux-64     836kB
  - libsolv      0.7.22  h6239696_0       conda-forge              454kB
  + libsolv      0.7.23  h3eb15da_0       conda-forge/linux-64     462kB

  Summary:

  Change: 4 packages
  Upgrade: 2 packages

  Total download: 3MB

──────────────────────────────────────────────────────────────────────────
```
----
```
❯ micromamba install mamba=1.3

conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache

Pinned packages:
  - python 3.10.*


Transaction

  Prefix: /opt/mambaforge/envs/quantdev

  Updating specs:

   - mamba=1.3


  Package       Version  Build            Channel                   Size
──────────────────────────────────────────────────────────────────────────
  Remove:
──────────────────────────────────────────────────────────────────────────

  - boa          0.14.0  pyhd8ed1ab_1     conda-forge               63kB

  Upgrade:
──────────────────────────────────────────────────────────────────────────

  - libarchive    3.5.2  hada088e_3       conda-forge                2MB
  + libarchive    3.6.2  h3d51595_0       conda-forge/linux-64     836kB
  - libmamba      1.1.0  h70b1f8a_2       conda-forge                1MB
  + libmamba      1.3.0  hcea66bb_0       conda-forge/linux-64       1MB
  - libmambapy    1.1.0  py310h69aa5bf_2  conda-forge              315kB
  + libmambapy    1.3.0  py310h1428755_0  conda-forge/linux-64     269kB
  - libsolv      0.7.22  h6239696_0       conda-forge              454kB
  + libsolv      0.7.23  h3eb15da_0       conda-forge/linux-64     462kB
  - mamba         1.1.0  py310h51d5547_2  conda-forge               49kB
  + mamba         1.3.0  py310h51d5547_0  conda-forge/linux-64      50kB

  Summary:

  Remove: 1 packages
  Upgrade: 5 packages

  Total download: 3MB

──────────────────────────────────────────────────────────────────────────
```

**Comment by isuruf** [comment]
I think we need to add `libsolv<0.7.23` constraint to all previous boa builds.

**Comment by isuruf** [comment]
See https://github.com/conda-forge/boa-feedstock/pull/61

**Pull request merged**
