### PR TITLE
relax pin to allow for installing with mamba 0.18

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Hooray `mamba 0.18`!

Boo no clear upstream pin in `boa`'s `setup.py` on the `mamba` version!

Figured I'd try this here... I don't know what i don't know about the validity of it!

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by wolfv** [comment]
Niooooooooooooooo

**Comment by wolfv** [comment]
Api changed a lot actually so we need to fix boa. Thanks for the effort though!

There are a bunch of import statements that have moved from `mamba_api` to `libmambapy` :)

**Comment by bollwyvl** [comment]
Can't say i didn't try!

**Comment by wolfv** [comment]
We'll try to get this sorted early tomorrow :)

**Pull request closed without merging**
